if(jQuery){var originalFn=$.fn.data;$.fn.data=function(){if(arguments[0]!=='$binding')
return originalFn.apply(this,arguments);}}
var showHideLoad=function(hideIndicator){if(typeof hideIndicator==="undefined"||hideIndicator===null){$('#overlay').show();}else{$('#overlay').hide();}}
var showHideLoadEzz=function(hideIndicator,txtC){var txt="جاري التحميل ...";if(typeof txtC!=="undefined"||txtC!==null)txt=txtC;if(typeof hideIndicator==="undefined"||hideIndicator===null){$('#bCText').html(txt);$('#bottomCircular').show();}else{$('#bottomCircular').hide();}}
var showloadEzz=function(txtC){showHideLoadEzz(null,txtC);}
function goTop(){$("html,body").animate({scrollTop:0},500);}
var OraSchool=angular.module('OraSchool',['ngRoute','angularUtils.directives.dirPagination','moment-picker','ngSanitize','chart.js']).run(function($http,dataFactory,$rootScope,$q,$timeout,$location){$rootScope.title=" |  الإدارة العامة للاختبارات ";$rootScope.defaultAcademicYear=function(){angular.forEach($rootScope.dashboardData.academicYear,function(item){if(item.isDefault=="1"){return item.id;}});}
$rootScope.icons=false;$rootScope.selects={};$rootScope.reports=[];$rootScope.rat_cancel=function(){$rootScope.rate_model=!$rootScope.rate_model;}
$rootScope.getSelect=function(id){if(typeof $rootScope.selects[id]==="undefined")
dataFactory.httpRequest('index.php/admin/getfilters/'+id).then(function(data){$rootScope.selects[id]=data;});}
$rootScope.can=function(perm){if($rootScope.dashboardData.perms.indexOf(perm)!==-1){return true}
return false;}
$rootScope.showIcons=function(){if($rootScope.icons==false){dataFactory.httpRequest('index.php/admin/icons').then(function(data){$rootScope.icons=data;$rootScope.modalClass="modal-lg";$rootScope.showIconsView=!$rootScope.showIconsView;});}else{$rootScope.modalClass="modal-lg";$rootScope.showIconsView=!$rootScope.showIconsView;}}});OraSchool.config(['momentPickerProvider',function(momentPickerProvider){momentPickerProvider.options({hoursFormat:'hh:mm a',minutesFormat:'hh:mm a',});}]);OraSchool.config(['ChartJsProvider',function(ChartJsProvider){ChartJsProvider.setOptions({colors:['rgba(0, 150, 136, 0.4)','rgba(255, 87, 34, 0.33)','rgba(158, 158, 158, 0.43)','rgba(3, 169, 244, 0.47)','rgba(233, 30, 99, 0.3)','rgba(255, 152, 0, 0.37)','rgba(205, 220, 57, 0.33)','rgba(63, 81, 181, 0.33)','#17a2b8','#fd7e14','#6f42c1','#e83e8c','#20c997','#ffc107','#28a745','#e83e8c','#007bff',]});ChartJsProvider.setOptions('doughnut',{cutoutPercentage:60});ChartJsProvider.setOptions('bubble',{tooltips:{enabled:false}});}]);var appBaseUrl=$('base').attr('href');OraSchool.controller('testController',function(dataFactory,$scope,$filter){});OraSchool.filter('ezzrange',function(){return function(input,total,ix){ix=parseInt(ix);total=parseInt(total);for(var i=ix;i<total;i++)
input.push(i);return input;};}).filter('ezzrange2',function(){return function(input,total,ix){ix=parseInt(ix);total=parseInt(total);for(var i=0;i<total;i++)
input.push(i+ix);return input;};}).filter('ezzrange3',function(){return function(input,total,ix){ix=parseInt(ix);total=parseInt(total);var xxx=ix;input.push(xxx);for(var i=1;i<total;i++){xxx=xxx+4;input.push(xxx);}
return input;};});OraSchool.controller('bk2',function(dataFactory,$scope,$filter){$scope.view={};$scope.row1=[];$scope.selectedSeatList={};$scope.view.add=false;$scope.selectedSeat={};$scope.noallowd=true;$scope.$watch('selectedSeat.phone',function(value,oldValue){value=String(value);var number=value.replace(/[^0-9]+/g,'');$scope.selectedSeat.phone=number;});$scope.isAllow=function(seat,index,beside){if($scope.noallowd){if(is_undefined(seat)){return false;}
else if(seat.status==='empty'){return false;}else if(seat.status==='Sold'){return false;}else if(seat.status==='Reserved'){return false;}
if(!is_undefined(seat)){if(!is_undefined(seat.number)){if($scope.inTemp(seat.number)){return false;}}}}
return true;}
$scope.selectSeat=function(seat,index,beside){if($scope.isAllow(seat,index,beside)){$scope.selectedSeat.passenger=undefined;$scope.selectedSeat.phone=undefined;$scope.selectedSeat.status=undefined;$scope.selectedSeat.gander=undefined;angular.forEach(seat,function(v,key){$scope.selectedSeat[key]=v;});$scope.selectedSeat['index']=index;}}
$scope.inTemp=function(perm){if($scope.selectedSeatList[perm]!==undefined){return true}
return false;}
$scope.getClass=function(seat,index,beside){var classList='';var ganderClass='';var noallowd=' noooo ';if($scope.noallowd)
noallowd=' noooo ';if(!is_undefined(seat)){if(seat.gander=='f')
ganderClass='f';}
if(is_undefined(seat)){classList='null';}
else if(seat.status==='empty'){classList='null';}else if(seat.status==='Sold'){classList='sold'+ganderClass+noallowd;}else if(seat.status==='Reserved'){classList='reserved'+ganderClass+noallowd;}
if(!is_undefined(seat)){if(!is_undefined(seat.number)){if(seat.number===$scope.selectedSeat.number){classList='selected '+classList;}
if($scope.inTemp(seat.number)){classList=classList+' tempselect'+noallowd;}}}
return classList;}
$scope.deleteSeat=function(seat){};$scope.removeSeatList=function(o,index){delete $scope.selectedSeatList[o.number];}
$scope.editSeatList=function(o,index){$scope.selectedSeat=o;delete $scope.selectedSeatList[o.number];}
$scope.startAdd=function(type){$scope.view.add=false;$scope.selectedSeatList={};$scope.selectedSeat={};$scope.view.add=type;}
$scope.cancelAdd=function(){$scope.view.add=false;$scope.selectedSeatList={};$scope.selectedSeat={};}
$scope.startAddGroup=function(parentData){$scope.parentData={};$scope.parentData=parentData;$scope.parentData.addmembers=true;$scope.selectedSeat={};}
$scope.addtoListSeat=function(seat){if(seat.number!==undefined){if($scope.selectedSeatList[seat.number]==undefined)
$scope.selectedSeatList[seat.number]={};$scope.selectedSeatList[seat.number]=seat;$scope.selectedSeat={};}};$scope.totalStatus=function(status){return[$scope.row1].map(function(aisle){return aisle.reduce(function(total,seat){return total+(seat.status===status);},0);}).reduce(function(a,b){return a+b;});};dataFactory.httpRequest('index.php/admin/getraws').then(function(data){$scope.row1=data;});});OraSchool.controller('bk',function(dataFactory,$scope,$filter){var vm=$scope;vm.row1=[];vm.selectedSeatList=[];vm.selectedSeat={};vm.$watch('selectedSeat.phone',function(value,oldValue){value=String(value);var number=value.replace(/[^0-9]+/g,'');vm.selectedSeat.phone=number;});vm.selectSeat=function(seat){vm.selectedSeat=seat;}
vm.deleteSeat=function(seat){if(seat.number!==undefined){seat.passenger=undefined;seat.phone=undefined;seat.status=undefined;vm.selectedSeat={};}};vm.addtoListSeat=function(seat){if(seat.number!==undefined){vm.selectedSeatList.push(seat);vm.selectedSeat={};}};vm.totalStatus=function(status){return[vm.row1].map(function(aisle){return aisle.reduce(function(total,seat){return total+(seat.status===status);},0);}).reduce(function(a,b){return a+b;});};dataFactory.httpRequest('index.php/admin/getraws').then(function(data){vm.row1=data;});});OraSchool.controller('mainController',function(dataFactory,$rootScope,$route,$scope){$scope.rows=[];var hbar={title:'hbar',type:'hbar',labels:['a','b','c'],colors:getColors(),data:[18647,19572,20892,],series:[],options:getBarOptions(""),};var hbarMulti={title:'hbar',type:'hbar',labels:['a','b','c'],colors:getColors(),data:[[18647,19572,20892,],[18647,19572,20892,],[18647,19572,20892,]],series:["type1","type2","type3"],options:getBarOptions(""),};var pie={title:"pie",type:'pie',labels:["a","b"],colors:getColors2(),data:[10,30],series:[],options:getCircleOptions("pie"),};var barMulti={title:'bar',type:'bar',labels:["a","b","c"],colors:getColors2(),data:[[18647,19572,20892,],[18647,19572,20892,],[18647,19572,20892,]],series:["taype1","taype2","taype3"],options:getBarOptions("",true),};var bar={title:'bar',type:'bar',labels:["a","b","c"],colors:getColors2(),data:[18647,19572,20892,],series:[],options:getBarOptions("اعداد الطلاب"),};var circle={title:"doughnut",type:'doughnut',labels:["a","b"],data:[11111,2222],colors:getColors(),series:[],options:getCircleOptions(""),};$scope.rows.push(hbar);$scope.rows.push(hbarMulti);$scope.rows.push(barMulti);$scope.rows.push(pie);$scope.rows.push(bar);$scope.rows.push(circle);$scope.chgAcYearModal=function(){$scope.modalTitle=$scope.phrase.chgYear;$scope.chgAcYearModalShow=!$scope.chgAcYearModalShow;}
$scope.page_title="mainController";$scope.adminHasPerm=function(perm){return $rootScope.dashboardData.perms.some(function(s){return s.indexOf(perm)>-1;});}
$scope.printPdfddd=function(id){var reportPageHeight=$('#'+id).innerHeight();var reportPageWidth=$('#'+id).innerWidth();var pdfCanvas=$('<canvas />').attr({id:"canvaspdf",width:reportPageWidth,height:reportPageHeight});var pdfctx=$(pdfCanvas)[0].getContext('2d');var pdfctxX=0;var pdfctxY=0;var buffer=100;var canvasHeight=$(this).innerHeight();var canvasWidth=$(this).innerWidth();pdfctx.drawImage($(this)[0],pdfctxX,pdfctxY,canvasWidth,canvasHeight);var pdf=new jsPDF('l','pt',[reportPageWidth,reportPageHeight]);pdf.addImage($(pdfCanvas)[0],'PNG',0,0);pdf.save('filename.pdf');}
$scope.printPdf=function(id){$('.no-print').hide();const elementToPrint=document.getElementById(id);const pdf=new jsPDF('p','pt',"a4");var options={};pdf.addHTML(elementToPrint,options,function()
{pdf.save('ورقة.pdf');});$('.no-print').show();}
$scope.printImage=function(id,img){var url_base64jp=document.getElementById(id).toDataURL("image/jpg");var a=document.getElementById(img);a.href=url_base64jp;}
$scope.printPdfffffff=function(id){$('.no-print').hide();const elementToPrint=document.getElementById(id);const pdf=new jsPDF('p','pt',"a4");pdf.addHTML(elementToPrint,()=>{pdf.save('ورقة.pdf');});$('.no-print').show();}
$scope.printPdfOne=function(id){var reportPageHeight=$('#'+id).innerHeight();var reportPageWidth=$('#'+id).innerWidth();const elementToPrint=document.getElementById(id);const pdf=new jsPDF('l','pt',[reportPageWidth,reportPageHeight]);pdf.addHTML(elementToPrint,()=>{pdf.save('ورقة.pdf');});}
$scope.printPdfold=function(){var reportPageHeight=$('#reportPage').innerHeight();var reportPageWidth=$('#reportPage').innerWidth();var pdfCanvas=$('<canvas />').attr({id:"canvaspdf",width:reportPageWidth,height:reportPageHeight});var pdfctx=$(pdfCanvas)[0].getContext('2d');var pdfctxX=0;var pdfctxY=0;var buffer=100;$("canvas").each(function(index){var canvasHeight=$(this).innerHeight();var canvasWidth=$(this).innerWidth();pdfctx.drawImage($(this)[0],pdfctxX,pdfctxY,canvasWidth,canvasHeight);pdfctxX+=canvasWidth+buffer;if(index%2===1){pdfctxX=0;pdfctxY+=canvasHeight+buffer;}});var pdf=new jsPDF('l','pt',[reportPageWidth,reportPageHeight]);pdf.addImage($(pdfCanvas)[0],'PNG',0,0);pdf.save('filename.pdf');};$scope.changeTheme=function(theme){$('#theme').attr({href:'assets/css/colors/'+theme+'.css'})
$rootScope.dashboardData.baseUser.defTheme=theme;var updatePost={'spec':'defTheme','value':theme};dataFactory.httpRequest('index.php/admin/admin/accountSettings/profile','POST',{},updatePost).then(function(data){response=apiResponse(data,'edit');});$('#themecolors').on('click','a',function(){$('#themecolors li a').removeClass('working');$(this).addClass('working')});}
showHideLoad(true);});OraSchool.controller('dashboardController',function(dataFactory,$rootScope,$scope){$scope.stats={};goTop();$scope.reports=$rootScope.reports;dataFactory.httpRequest('index.php/admin/reportsAll','POST',{},{}).then(function(data){$scope.reports=data;$rootScope.reports=data;showHideLoad(true);});dataFactory.httpRequest('index.php/admin/overviews').then(function(data){$rootScope.dashboardData.overviews=data;showHideLoad(true);});});OraSchool.controller('tableController',function(dataFactory,$scope,$sce,$rootScope,$route){$scope.items={};$scope.filters={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.searchInput={};$scope.userRole=$rootScope.dashboardData.role;$scope.cur_page=1;$scope.fffiles="";var methodName=$route.current.methodName;$scope.totalItems=0;$scope.methodName=$route.current.methodName;$scope.hasFile=function(v){$scope.fffiles=$scope.fffiles+v+",";}
$scope.listItems=function(pageNumber){showHideLoad();var init='';if(pageNumber==-1){pageNumber=1;init="?init=1";}
dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'List/listAll/'+pageNumber+init).then(function(data){if(!(typeof data=='undefined')){$scope.items=data.items;if(!(typeof data.filters=="undefined")){$scope.filters=data.filters;}
if(!(typeof data.init=="undefined")){$scope.init=data.init;}
if(!(typeof data.totalItems=="undefined")){$scope.totalItems=data.totalItems;}}
showHideLoad(true);});}
$scope.searchDB=function(pageNumber){showHideLoad();$scope.cur_page=pageNumber;dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'List/listAll/'+pageNumber,'POST',{},{'searchInput':$scope.searchInput}).then(function(data){if(!(typeof data=='undefined')){$scope.items=data.items;if(!(typeof data.totalItems=="undefined")){$scope.totalItems=data.totalItems;}}
showHideLoad(true);});}
$scope.searchDB2=function(pageNumber){$scope.currentPage=pageNumber;$scope.getResultsPage(pageNumber);}
$scope.saveImported=function(content){dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/import','POST',{},$scope.formImport,"import,").then(function(data){data=apiResponse(data);if(typeof data.status!="undefined"){if(data.status=="success"){$scope.changeView('list');}}});showHideLoad(true);}
$scope.getResultsPage=function(id){if(typeof id=="undefined"){id=$scope.cur_page;}
if(id==-1)
$scope.cur_page=1;else
$scope.cur_page=id;if(!jQuery.isEmptyObject($scope.searchInput)){$scope.searchDB(id);}else{$scope.listItems(id);}}
$scope.getResultsPage(-1);$scope.showModal=false;$scope.save_publish=function(){if($scope.views.add){$scope.saveAdd();}else{$scope.saveEdit();}}
$scope.saveAdd=function(){showHideLoad();if($scope.fffiles!=""){dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'','POST',{},$scope.form,$scope.fffiles).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}else{dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}}
$scope.saveEdit=function(){showHideLoad();if($scope.fffiles!=""){dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/'+$scope.form.id,'POST',{},$scope.form,$scope.fffiles).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}else{dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/'+$scope.form.id,'POST',{},$scope.form).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}}
$scope.remove=function(item,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/delete/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.items.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/'+id).then(function(data){$scope.form=data;$scope.changeView('edit');showHideLoad(true);});}
$scope.changeStatus=function(item,$index){if(item.active==2)
msg="سيتم الموافقة على الطلب  هل انت متأكد ؟";else if(item.active==1)
msg="سيتم التعطيل  هل انت متأكد ؟";else if(item.active==0)
msg="سيتم التفعيل  هل انت متأكد ؟";else
msg="سيتم تغيير حالة العنصر  هل انت متأكد ؟";$.confirm({title:'تغيير حالة العنصر ؟؟',content:msg,type:'blue',buttons:{yes:{text:"حسنا",btnClass:'btn-blue',keys:['enter'],action:function(){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/active/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.items[$index].active=data.active;}
showHideLoad(true);});}},cancel:{text:"الغاء",function(){return false;}}}});}
$scope.changeStatusReq=function(item,$index){if(item.active==2)
msg="سيتم الغاء  الطلب  هل انت متأكد ؟";else if(item.active==0)
msg="سيتم  ارسال طلب تفعيل  هل انت متأكد ؟";else
msg="سيتم تغيير حالة العنصر  هل انت متأكد ؟";$.confirm({title:'تغيير حالة العنصر ؟؟',content:msg,type:'blue',buttons:{yes:{text:"حسنا",btnClass:'btn-blue',keys:['enter'],action:function(){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/activereq/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.items[$index].active=data.active;}
showHideLoad(true);});}},cancel:{text:"الغاء",function(){return false;}}}});}
$scope.changeStatusRdeq=function(item,$index){if(item.active==2)
msg="سيتم الغاء  الطلب  هل انت متأكد ؟";else if(item.active==0)
msg="سيتم  ارسال طلب تفعيل  هل انت متأكد ؟";else
msg="سيتم تغيير حالة العنصر  هل انت متأكد ؟";var confirmRemove=confirm();if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/activereq/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.items[$index].active=data.active;}
showHideLoad(true);});}}
$scope.viewDetails=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/view/'+id).then(function(data){$scope.itemView=data.rows;$scope.itemTitle=data.title;$scope.changeView('view');showHideLoad(true);});}
$scope.userProfile=function(id){dataFactory.httpRequest('index.php/admin/user/profile/'+id).then(function(data){$scope.modalTitle=data.title;$scope.modalContent=$sce.trustAsHtml(data.content);$scope.showModal=!$scope.showModal;});};$scope.resetSearch=function(){$scope.searchInput={};$scope.getResultsPage(1);}
$scope.pageChanged=function(newPage){$scope.getResultsPage(newPage);};$scope.import=function(){$scope.changeView('import');};$scope.changeView=function(view){goTop();if(view=="add"||view=="list"||view=="show"){$scope.form={};}
if(view=="import"){$scope.formImport={};}
angular.forEach($scope.views,function(v,key){$scope.views[key]=false;});$scope.views[view]=true;}});OraSchool.controller('tablesController',function(dataFactory,$scope,$sce,$rootScope,$route){$scope.items={};$scope.filters={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.searchInput={};$scope.userRole=$rootScope.dashboardData.role;$scope.cur_page=1;var methodName=$route.current.methodName;$scope.totalItems=0;$scope.methodName=$route.current.methodName;$scope.listItems=function(pageNumber){showHideLoad();var init='';if(pageNumber==-1){pageNumber=1;init="?init=1";}
dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'List/listAll/'+pageNumber+init).then(function(data){if(!(typeof data==='undefined')){$scope.items=data.items;if(!(typeof data.filters=="undefined")){$scope.filters=data.filters;}
if(!(typeof data.totalItems=="undefined")){$scope.totalItems=data.totalItems;}}
showHideLoad(true);});}
$scope.addRaw=function(type,arr){if(typeof $scope.form[type]=="undefined"){$scope.form[type]={};}
showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/addRaw/'+type,'POST',{},$scope.form[arr]).then(function(data){$scope.form[arr]={};showHideLoad(true);if(typeof data.status!="undefined"){data=apiResponse(data);}
if(typeof data.raw!="undefined"){$scope.form[type].push(data.raw);}});}
$scope.refrech=function(){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+"List/refrech",'POST',{},{}).then(function(data){showHideLoad(true);if(typeof data.status!="undefined"){data=apiResponse(data);}});}
$scope.refrechTable=function(t){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+"/refrech/"+t,'POST',{},{}).then(function(data){showHideLoad(true);if(typeof data.status!="undefined"){data=apiResponse(data);}});}
$scope.toStatic=function(t){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+"/static/"+t,'POST',{},{}).then(function(data){apiResponse(data);if(typeof data.status!="undefined"){data=apiResponse(data);}
showHideLoad(true);$scope.getResultsPage();});}
$scope.toDyinamic=function(t){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+"/dyinamic/"+t,'POST',{},{}).then(function(data){showHideLoad(true);apiResponse(data);if(typeof data.status!="undefined"){data=apiResponse(data);}
showHideLoad(true);$scope.getResultsPage();});}
$scope.removeRaw=function(type,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){if(typeof $scope.form[type]!="undefined"){$scope.form[type].splice(index,1);}}}
$scope.searchDB=function(pageNumber){showHideLoad();$scope.cur_page=pageNumber;dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'List/listAll/'+pageNumber,'POST',{},{'searchInput':$scope.searchInput}).then(function(data){if(!(typeof data=='undefined')){$scope.items=data.items;if(!(typeof data.totalItems=="undefined")){$scope.totalItems=data.totalItems;}}
showHideLoad(true);});}
$scope.searchDB2=function(pageNumber){$scope.currentPage=pageNumber;$scope.getResultsPage(pageNumber);}
$scope.saveImported=function(content){dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/import','POST',{},$scope.formImport,"import,").then(function(data){data=apiResponse(data);if(typeof data.status!="undefined"){if(data.status=="success"){$scope.changeView('list');}}});showHideLoad(true);}
$scope.getResultsPage=function(id){if(typeof id=="undefined"){id=$scope.cur_page;}
if(id==-1)
$scope.cur_page=1;else
$scope.cur_page=id;if(!jQuery.isEmptyObject($scope.searchInput)){$scope.searchDB(id);}else{$scope.listItems(id);}}
$scope.getResultsPage(-1);$scope.showModal=false;$scope.save_publish=function(){if($scope.views.add){$scope.saveAdd();}else{$scope.saveEdit();}}
$scope.saveAdd=function(){showHideLoad();if(typeof $scope.form.file!="undefined"){dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'','POST',{},$scope.form,"file,").then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}else{dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}}
$scope.saveEdit=function(){showHideLoad();if(typeof $scope.form.file!="undefined"){dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/'+$scope.form.id,'POST',{},$scope.form,"file,").then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}else{dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/'+$scope.form.id,'POST',{},$scope.form).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}}
$scope.remove=function(item,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/delete/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.items.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/'+id).then(function(data){$scope.form=data;$scope.changeView('edit');showHideLoad(true);});}
$scope.viewDetails=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/'+$scope.methodName+'/view/'+id).then(function(data){$scope.itemView=data.rows;$scope.itemTitle=data.title;$scope.changeView('view');showHideLoad(true);});}
$scope.userProfile=function(id){dataFactory.httpRequest('index.php/admin/user/profile/'+id).then(function(data){$scope.modalTitle=data.title;$scope.modalContent=$sce.trustAsHtml(data.content);$scope.showModal=!$scope.showModal;});};$scope.resetSearch=function(){$scope.searchInput={};$scope.getResultsPage(1);}
$scope.pageChanged=function(newPage){$scope.getResultsPage(newPage);};$scope.import=function(){$scope.changeView('import');};$scope.changeView=function(view){goTop();if(view=="add"||view=="list"||view=="show"){$scope.form={};}
if(view=="import"){$scope.formImport={};}
angular.forEach($scope.views,function(v,key){$scope.views[key]=false;});$scope.views[view]=true;}});OraSchool.controller('studentsController',function(dataFactory,$scope,$sce,$rootScope,$route){$scope.students={};$scope.classes={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.invoice={};$scope.payDetails={};$scope.resultData={};$scope.searchInput={};$scope.userRole=$rootScope.dashboardData.role;$scope.cur_page=1;var methodName=$route.current.methodName;$scope.listInvoices=function(pageNumber){showHideLoad();dataFactory.httpRequest('index.php/admin/studentsList/listAll/'+pageNumber).then(function(data){$scope.students=data.students;$scope.classes=data.classes;$scope.cities=data.cities;$scope.years=data.years;$scope.showUser=data.showUser;$scope.totalItems=data.totalItems;$scope.currency_symbol=data.currency_symbol;showHideLoad(true);});}
$scope.searchDB=function(pageNumber){showHideLoad();dataFactory.httpRequest('index.php/admin/studentsList/listAll/'+pageNumber,'POST',{},{'searchInput':$scope.searchInput}).then(function(data){$scope.students=data.students;$scope.totalItems=data.totalItems;showHideLoad(true);});}
$scope.getResultsPage=function(id){if(typeof id=="undefined"){id=$scope.cur_page;}
$scope.cur_page=id;if(!jQuery.isEmptyObject($scope.searchInput)){$scope.searchDB(id);}else{$scope.listInvoices(id);}}
$scope.getResultsPage(1);$scope.showModal=false;$scope.userProfile=function(id){dataFactory.httpRequest('index.php/admin/user/profile/'+id).then(function(data){$scope.modalTitle=data.title;$scope.modalContent=$sce.trustAsHtml(data.content);$scope.showModal=!$scope.showModal;});};$scope.toggleSearch=function(){$('.advSearch').toggleClass('col-0 col-3 hidden',1000);$('.listContent').toggleClass('col-12 col-9',1000);}
$scope.resetSearch=function(){$scope.searchInput={};$scope.getResultsPage(1);}
$scope.totalItems=0;$scope.pageChanged=function(newPage){$scope.getResultsPage(newPage);};$scope.import=function(){$scope.changeView('import');};$scope.saveImported=function(content){dataFactory.httpRequest('index.php/admin/import/'+$scope.formx.impclass,'POST',{},$scope.formx,"import,").then(function(data){data=apiResponse(data);if(typeof data.status!="undefined"){if(data.status=="success"){$scope.changeView('list');}}});showHideLoad(true);}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views.invoice=false;$scope.views.import=false;$scope.views.details=false;$scope.views[view]=true;}});OraSchool.controller('adminsController',function(dataFactory,$rootScope,$scope){$scope.admins={};$scope.roles={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.form.comVia=["mail","sms","phone"];$scope.form.customPermissions=[];$scope.load_admins=function(){dataFactory.httpRequest('index.php/admin/admins/listAll').then(function(data){$scope.admins=data.admins;$scope.roles=data.roles;$scope.changeView('list');showHideLoad(true);});}
$scope.load_admins();$scope.saveAdd=function(content){response=apiResponse(content,'add');if(content.status=="success"){showHideLoad();$scope.load_admins();}
showHideLoad(true);}
$scope.remove=function(item,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admin/admins/delete/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.admins.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/admins/'+id).then(function(data){$scope.form=data;$scope.changeView('edit');showHideLoad(true);});}
$scope.hasPermission=function(permission){var caseNow=$.inArray(permission,$scope.form.customPermissions)>-1;return caseNow;}
$scope.saveEdit=function(content){response=apiResponse(content,'edit');if(content.status=="success"){showHideLoad();$scope.load_admins();}
showHideLoad(true);}
$scope.account_status=function(user_id,$index){showHideLoad();dataFactory.httpRequest('index.php/admin/admins/account_status/'+user_id,'POST',{},{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.admins[$index].account_active=response.account_active;}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.form.comVia=["mail","sms","phone"];}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.controller('employeesController',function(dataFactory,$rootScope,$scope){$scope.admins={};$scope.roles={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.form.comVia=["mail","sms","phone"];$scope.form.customPermissions=[];$scope.load_admins=function(){dataFactory.httpRequest('index.php/admin/employees/listAll').then(function(data){$scope.admins=data.admins;$scope.roles=data.roles;$scope.districtZone=data.districtZone;$scope.feeGroups=data.feeGroups;$scope.changeView('list');showHideLoad(true);});}
$scope.load_admins();$scope.saveAdd=function(data){showHideLoad();dataFactory.httpRequest('index.php/admin/employees','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.load_admins();$scope.changeView('list');}
showHideLoad(true);});}
$scope.saveEdit=function(data){dataFactory.httpRequest('index.php/admin/employees/'+$scope.form.id,'POST',{},$scope.form).then(function(data){showHideLoad();response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_admins();$scope.changeView('list');}
showHideLoad(true);});}
$scope.remove=function(item,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admin/employees/delete/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.admins.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/employees/'+id).then(function(data){$scope.form=data;$scope.changeView('edit');showHideLoad(true);});}
$scope.hasPermission=function(permission){var caseNow=$.inArray(permission,$scope.form.customPermissions)>-1;return caseNow;}
$scope.account_status=function(user_id,$index){showHideLoad();dataFactory.httpRequest('index.php/admin/employees/account_status/'+user_id,'POST',{},{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.admins[$index].account_active=response.account_active;}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.form.comVia=["mail","sms","phone"];}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.controller('usersController',function(dataFactory,$rootScope,$scope){$scope.admins={};$scope.roles={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.form.comVia=["mail","sms","phone"];$scope.form.customPermissions=[];$scope.load_admins=function(){dataFactory.httpRequest('index.php/admin/users/listAll').then(function(data){$scope.admins=data.admins;$scope.roles=data.roles;$scope.changeView('list');showHideLoad(true);});}
$scope.load_admins();$scope.saveAdd=function(data){showHideLoad();dataFactory.httpRequest('index.php/admin/users','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.load_admins();$scope.changeView('list');}
showHideLoad(true);});}
$scope.saveEdit=function(data){dataFactory.httpRequest('index.php/admin/users/'+$scope.form.id,'POST',{},$scope.form).then(function(data){showHideLoad();response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_admins();$scope.changeView('list');}
showHideLoad(true);});}
$scope.remove=function(item,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admin/users/delete/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.admins.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/users/'+id).then(function(data){$scope.form=data;$scope.changeView('edit');showHideLoad(true);});}
$scope.hasPermission=function(permission){var caseNow=$.inArray(permission,$scope.form.customPermissions)>-1;return caseNow;}
$scope.account_status=function(user_id,$index){showHideLoad();dataFactory.httpRequest('index.php/admin/users/account_status/'+user_id,'POST',{},{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.admins[$index].account_active=response.account_active;}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.form.comVia=["mail","sms","phone"];}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.controller('reportsController',function(dataFactory,$rootScope,$scope,$http,$sce){$scope.views={};$scope.views.list=true;$scope.searching=false;$scope.items=[];$scope.reports=[];$scope.reportsTemp=[];$scope.reportsList=[];$scope.searchInput={};$scope.report={};$scope.table={};$scope.hide={};$scope.titles={};$scope.filterText='';$scope.sort={column:'name',descending:false};$scope.unshaw=function(column){$scope.hide[column]=true;}
$scope.shaw=function(column){$scope.hide[column]=false;}
$scope.changeSorting=function(column){var sort=$scope.sort;if(sort.column==column){sort.descending=!sort.descending;}else{sort.column=column;sort.descending=false;}};$scope.loadData=function(){showHideLoad();dataFactory.httpRequest('index.php/admin/reports').then(function(data){showHideLoad(true);apiResponse(data,'edit');if(typeof data.status!="undefined"){if(data.status=="success"){if(typeof data.data!="undefined"){$scope.reportsList=data.data;}}}});}
$scope.loadData();$scope.selects={};$scope.searchClose=function(id){$scope.searchInput={};$scope.report=$scope.reportsTemp[$scope.report.id];}
$scope.searchDB=function(){showloadEzz("جاري البحث");$scope.searching=true;dataFactory.httpRequest('index.php/admin/report/'+$scope.report.id,'POST',{},{'searchInput':$scope.searchInput}).then(function(data){showHideLoadEzz(true);$scope.searching=false;apiResponse(data);$scope.loadReport(data,false);});}
$scope.loadReport=function(data,issearch){if(typeof data!=="undefined")
if(typeof data.status!="undefined"){if(data.status=="success"){if(typeof data.data!="undefined"){data=data.data;if(typeof data.items!="undefined")
$scope.report.items=data.items;if(typeof data.titles!="undefined")
$scope.report.titles=data.titles;if(typeof data.filters!="undefined")
$scope.report.filters=data.filters;$scope.report.reports=[];if(data.reports!=="undefined")
angular.forEach(data.reports,function(item){$scope.report.reports.push(getChartObject(item));});}}}
if(issearch){if(typeof $scope.report!="undefined")
if(typeof $scope.report.id!="undefined"){delete $scope.reportsTemp[$scope.report.id];$scope.reportsTemp[$scope.report.id]=CopyObject($scope.report);}}}
$scope.viewReport=function(rep){$scope.searching=false;$scope.hide={};$scope.searchInput={};$scope.items=[];$scope.titles=[];$scope.report={};$scope.report=rep;if(typeof $scope.reportsTemp[rep.id]==="undefined")
showloadEzz("جاري تحميل التقرير");else{showloadEzz("جاري تحديث التقرير");$scope.report=$scope.reportsTemp[rep.id];}
$scope.changeView('report');dataFactory.httpRequest('index.php/admin/report/'+rep.id).then(function(data){showHideLoadEzz(true);$scope.report=rep;apiResponse(data,'edit');$scope.loadReport(data,true);});};$scope.changeView=function(view){goTop();angular.forEach($scope.views,function(v,key){$scope.views[key]=false;});$scope.views[view]=true;}});OraSchool.controller('langController',function(dataFactory,$rootScope,$scope){$scope.languages={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.translate=function(){$(".phraseList label").each(function(i,current){var str=$(current).text();if($(current).children('input').val()==""){var str2=$(current).children('input').val(str);$(current).children('input').trigger('input');}});return;}
$scope.highlight=function(){$(".phraseList label").each(function(i,current){if($(current).children('input').val()==""){$(current).children('input').css('border','10px solid');}});return;}
$scope.addLangItemMulti=function(){var id=$scope.form.newMId;var newMulti=$scope.form.newMulti;var newOne=$scope.form.newOne;$scope.form.languagePhrases[id+'s']=newMulti;$scope.form.languagePhrases[id+'Title']='عنوان'+' '+'ال'+newOne;$scope.form.languagePhrases[id+'Content']='تفاصيل'+' '+'ال'+newOne;$scope.form.languagePhrases['add'+id]='اضافة'+' '+newOne;$scope.form.languagePhrases['edit'+id]='تعديل'+' '+newOne;$scope.form.languagePhrases['list'+id]='قائمة'+' '+listproduct;}
$scope.addLangItem=function(){$scope.form.languagePhrases[$scope.form.newId]=$scope.form.newName;}
dataFactory.httpRequest('index.php/admin/languages/listAll').then(function(data){$scope.languages=data;showHideLoad(true);});$scope.addLang=function(){$scope.form={};$scope.form.languagePhrases={};$scope.changeView('edit');}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/languages/'+id).then(function(data){$scope.changeView('edit');$scope.form=data;showHideLoad(true);});}
$scope.saveEdit=function(){if(typeof $scope.form.id=="undefined"){showHideLoad();dataFactory.httpRequest('index.php/admin/languages','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.languages.push(response);$scope.changeView('list');}
showHideLoad(true);});}else{showHideLoad();dataFactory.httpRequest('index.php/admin/languages/'+$scope.form.id,'POST',{},$scope.form).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.languages=apiModifyTable($scope.languages,response.id,response);$scope.changeView('list');}
showHideLoad(true);});}}
$scope.remove=function(item,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admin/languages/delete/'+item.id,'POST',{},$scope.form).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.languages.splice(index,1);}
showHideLoad(true);});}}
$scope.saveAdd=function(){}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.factory('srvLibrary',['$http','$rootScope',function($http,$rootScope){var sdo={getEssentials:function(){if(typeof($rootScope.dashboardData)=="undefined"){var promise=$http({method:'GET',url:'index.php/admin/dashboard'});promise.success(function(data,status,headers,conf){$rootScope.dashboardData=data;$rootScope.phrase=$rootScope.dashboardData.language;$rootScope.angDateFormat=$rootScope.dashboardData.dateformat;if($rootScope.angDateFormat==""){$rootScope.angDateFormat="MM/dd/yyyy";}else{$rootScope.angDateFormat=$rootScope.angDateFormat.replace('d','dd');$rootScope.angDateFormat=$rootScope.angDateFormat.replace('m','MM');$rootScope.angDateFormat=$rootScope.angDateFormat.replace('Y','yyyy');}
if($rootScope.dashboardData.gcalendar=="ethiopic"){$rootScope.dashboardData.gcalendar="ethiopian";}
return true;});return promise;}else{return true;}}}
return sdo;}]);OraSchool.controller('newsboardController',function(dataFactory,$routeParams,$sce,$rootScope,$scope){});OraSchool.controller('accountSettingsController',function(dataFactory,$rootScope,$scope,$route){$scope.account={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.languages={};$scope.languageAllow;var methodName=$route.current.methodName;$scope.changeView=function(view){if(view=="list"||view=="show"){$scope.form={};}
$scope.views.profile=false;$scope.views.email=false;$scope.views.password=false;$scope.views.invoices=false;$scope.views.invoiceDetails=false;$scope.views[view]=true;}
if(methodName=="profile"){dataFactory.httpRequest('index.php/admin/accountSettings/langs').then(function(data){$scope.languages=data.languages;$scope.languageAllow=data.languageAllow;$scope.layoutColorUserChange=data.layoutColorUserChange;showHideLoad(true);});dataFactory.httpRequest('index.php/admin/accountSettings/data').then(function(data){$scope.form=data;$scope.oldThemeVal=data.defTheme;$scope.defLang=data.defLang;$scope.changeView('profile');showHideLoad(true);});}else if(methodName=="email"){$scope.form={};$scope.changeView('email');showHideLoad(true);}else if(methodName=="password"){$scope.form={};$scope.changeView('password');showHideLoad(true);}else if(methodName=="invoices"){dataFactory.httpRequest('index.php/admin/accountSettings/invoices').then(function(data){$scope.invoices=data.invoices;$scope.changeView('invoices');showHideLoad(true);});}
$scope.seeInvoice=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/accountSettings/invoices/'+id).then(function(data){$scope.invoice=data;$scope.changeView('invoiceDetails');showHideLoad(true);});}
$scope.payOnline=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/invoices/invoice/'+id).then(function(data){$scope.invoice=data;$scope.modalTitle="Pay Invoice Online";$scope.payOnlineModal=!$scope.payOnlineModal;showHideLoad(true);});}
$scope.payOnlineNow=function(id){$scope.form.invoice=id;}
$scope.saveEmail=function(){if($scope.form.email!=$scope.form.reemail){alert($rootScope.phrase.mailReMailDontMatch);}else{showHideLoad();dataFactory.httpRequest('index.php/admin/accountSettings/email','POST',{},$scope.form).then(function(data){response=apiResponse(data,'edit');showHideLoad(true);});}}
$scope.savePassword=function(){if($scope.form.newPassword!=$scope.form.repassword){alert($rootScope.phrase.passRepassDontMatch);}else{showHideLoad();dataFactory.httpRequest('index.php/admin/accountSettings/password','POST',{},$scope.form).then(function(data){response=apiResponse(data,'edit');showHideLoad(true);});}}
$scope.saveProfile=function(data){response=apiResponse(data,'edit');if(response){if($scope.form.defTheme!=$scope.oldThemeVal){location.reload();}
if($scope.form.defLang!=$scope.defLang){location.reload();}
$scope.form=response;}
showHideLoad(true);}});OraSchool.controller('settingsController',function(dataFactory,$rootScope,$scope,$route){$scope.views={};$scope.form={};$scope.languages={};$scope.newDayOff;var methodName=$route.current.methodName;$scope.oldThemeVal;$scope.changeView=function(view){$scope.views.settings=false;$scope.views.terms=false;$scope.views[view]=true;}
if(methodName=="settings"){dataFactory.httpRequest('index.php/admin/siteSettings/langs').then(function(data){$scope.languages=data.languages;showHideLoad(true);});dataFactory.httpRequest('index.php/admin/siteSettings/siteSettings').then(function(data){$scope.form=data.settings;$scope.timezone_list=data.timezone_list;$scope.formS=data.smsProvider;$scope.formM=data.mailProvider;$scope.oldThemeVal=$scope.form.layoutColor;$scope.globalcalendars=data.globalcalendars;$scope.biometric_device_status=data.biometric_device_status;showHideLoad(true);});$scope.changeView('settings');}else if(methodName=="terms"){dataFactory.httpRequest('index.php/admin/siteSettings/terms').then(function(data){$scope.form=data;showHideLoad(true);});$scope.changeView('terms');}
$scope.isDaySelected=function(arrayData,valueData){return arrayData.indexOf(valueData)>-1;}
$scope.officialVacationDayAdd=function(){if($scope.newDayOff==''||typeof $scope.newDayOff==="undefined"){return;}
$scope.form.officialVacationDay.push($scope.newDayOff);}
$scope.removeVacationDay=function(item,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){$scope.form.officialVacationDay.splice(index,1);}}
$scope.moduleActivated=function(module){return $.inArray(module,$scope.form.activatedModules)>-1;}
$scope.saveEdit=function(){showHideLoad();$scope.form.smsProvider=$scope.formS;$scope.form.mailProvider=$scope.formM;dataFactory.httpRequest('index.php/admin/siteSettings/siteSettings','POST',{},$scope.form).then(function(data){response=apiResponse(data,'edit');location.reload();showHideLoad(true);});}
$scope.saveTerms=function(){showHideLoad();dataFactory.httpRequest('index.php/admin/siteSettings/terms','POST',{},$scope.form).then(function(data){response=apiResponse(data,'edit');showHideLoad(true);});}
$scope.test_mail_function=function(){$scope.modalTitle="Test Mail Function";$scope.test_mail_function_modal=!$scope.test_mail_function_modal;$scope.testmailform={};}
$scope.test_mail_function_action=function(){showHideLoad();dataFactory.httpRequest('index.php/admin/siteSettings/test_mail_function','POST',{},$scope.testmailform).then(function(server_response){alert("Server Response : "+server_response.message);$scope.test_mail_function_modal=!$scope.test_mail_function_modal;showHideLoad(true);});}
$scope.test_sms_function=function(){$scope.modalTitle="Test SMS Function";$scope.test_sms_function_modal=!$scope.test_sms_function_modal;$scope.testsmsform={};}
$scope.test_sms_function_action=function(){showHideLoad();dataFactory.httpRequest('index.php/admin/siteSettings/test_sms_function','POST',{},$scope.testsmsform).then(function(server_response){alert("Server Response : "+server_response.message);$scope.test_sms_function_modal=!$scope.test_sms_function_modal;showHideLoad(true);});}});OraSchool.controller('messagesController',function(dataFactory,$rootScope,$route,$scope,$location,$routeParams){$scope.messages={};$scope.message={};$scope.messageDet={};$scope.totalItems=0;$scope.views={};$scope.views.list=true;$scope.selectedAll=false;$scope.searchUsers=false;$scope.repeatCheck=true;$scope.form={};$scope.messageBefore;$scope.messageAfter;$scope.searchResults={};var routeData=$route.current;var currentMessageRefreshId;var messageId;$scope.totalItems=0;$scope.pageChanged=function(newPage){getResultsPage(newPage);};$scope.showMessage=function(id){$scope.repeatCheck=true;showHideLoad();dataFactory.httpRequest('index.php/admin/messages/'+id).then(function(data){data=successOrError(data);if(data){messageId=id;$scope.changeView('read');$scope.message=data.messages.reverse();$scope.messageDet=data.messageDet;if($scope.message[0]){$scope.messageBefore=$scope.message[0].dateSent;}
if($scope.message[$scope.message.length-1]){$scope.messageAfter=$scope.message[$scope.message.length-1].dateSent;}
currentMessageRefreshId=setInterval(currentMessagePull,2000);$("#chat-box").slimScroll({scrollTo:$("#chat-box").prop('scrollHeight')+'px'});}
showHideLoad(true);});}
getResultsPage(1);if($routeParams.messageId){$scope.showMessage($routeParams.messageId);}
function getResultsPage(pageNumber){dataFactory.httpRequest('index.php/admin/messages/listAll/'+pageNumber).then(function(data){$scope.messages=data.messages;$scope.totalItems=data.totalItems;showHideLoad(true);});}
$scope.linkUser=function(){$scope.modalTitle=$rootScope.phrase.searchUsers;$scope.searchUsers=!$scope.searchUsers;}
$scope.searchUserButton=function(){var searchAbout=$('#searchKeyword').val();if(searchAbout.length<3){alert($rootScope.phrase.minCharLength3);return;}
dataFactory.httpRequest('index.php/admin/messages/searchUser/'+searchAbout).then(function(data){$scope.searchResults=data;});}
$scope.linkStudentFinish=function(student){if(typeof $scope.form.toId=="undefined"){$scope.form.toId=[];}
$scope.form.toId.push(student);$scope.searchUsers=!$scope.searchUsers;}
$scope.checkAll=function(){$scope.selectedAll=!$scope.selectedAll;angular.forEach($scope.messages,function(item){item.selected=$scope.selectedAll;});}
$scope.loadOld=function(){dataFactory.httpRequest('index.php/admin/messages/before/'+$scope.messageDet.fromId+'/'+$scope.messageDet.toId+'/'+$scope.messageBefore).then(function(data){angular.forEach(data,function(item){$scope.message.splice(0,0,item);});if(data.length==0){$('#loadOld').hide();}
$scope.messageBefore=$scope.message[0].dateSent;});}
$scope.markRead=function(){$scope.form.items=[];angular.forEach($scope.messages,function(item,key){if($scope.messages[key].selected){$scope.form.items.push(item.id);$scope.messages[key].messageStatus=0;}});dataFactory.httpRequest('index.php/admin/messages/read',"POST",{},$scope.form).then(function(data){response=apiResponse(data,'edit');});}
$scope.markUnRead=function(){$scope.form.items=[];angular.forEach($scope.messages,function(item,key){if($scope.messages[key].selected){$scope.form.items.push(item.id);$scope.messages[key].messageStatus=1;}});dataFactory.httpRequest('index.php/admin/messages/unread',"POST",{},$scope.form).then(function(data){response=apiResponse(data,'edit');});}
$scope.markDelete=function(){$scope.form.items=[];var len=$scope.messages.length
while(len--){if($scope.messages[len].selected){$scope.form.items.push($scope.messages[len].id);$scope.messages.splice(len,1);}}
dataFactory.httpRequest('index.php/admin/messages/delete',"POST",{},$scope.form).then(function(data){response=apiResponse(data,'remove');});}
var currentMessagePull=function(){if('#/messages/'+messageId==location.hash){dataFactory.httpRequest('index.php/admin/messages/ajax/'+$scope.messageDet.fromId+'/'+$scope.messageDet.toId+'/'+$scope.messageAfter).then(function(data){angular.forEach(data,function(item){$scope.message.push(item);var newH=parseInt($("#chat-box").prop('scrollHeight'))+100;$("#chat-box").slimScroll({scrollTo:newH+'px'});});if($scope.message[$scope.message.length-1]){$scope.messageAfter=$scope.message[$scope.message.length-1].dateSent;}});}else{clearInterval(currentMessageRefreshId);}};$scope.replyMessage=function(){if($scope.form.reply!=""&&typeof $scope.form.reply!="undefined"){$scope.form.disable=true;$scope.form.toId=$scope.messageDet.toId;dataFactory.httpRequest('index.php/admin/messages/'+$scope.messageDet.id,'POST',{},$scope.form).then(function(data){$("#chat-box").slimScroll({scrollTo:$("#chat-box").prop('scrollHeight')+'px'});$scope.form={};});}}
$scope.sendMessageNow=function(){dataFactory.httpRequest('index.php/admin/messages','POST',{},$scope.form).then(function(data){if(data.messageId=="home"){getResultsPage(1);$scope.changeView('list');}else{$location.path('/messages/'+data.messageId);}});}
$scope.changeView=function(view){if(view=="read"||view=="list"||view=="create"){$scope.form={};}
if(view=="list"||view=="create"){clearInterval(currentMessageRefreshId);}
$scope.views.list=false;$scope.views.read=false;$scope.views.create=false;$scope.views[view]=true;}});OraSchool.controller('pollsController',function(dataFactory,$scope,$rootScope){$scope.polls={};$scope.views={};$scope.views.list=true;$scope.form={};dataFactory.httpRequest('index.php/admin/polls/listAll').then(function(data){$scope.polls=data;showHideLoad(true);});$scope.remove=function(item,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admin/polls/delete/'+item.id,'POST').then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.polls.splice(index,1);}
showHideLoad(true);});}}
$scope.addPollOption=function(item){var optionTitle=prompt($rootScope.phrase.voteOptionTitle);if(optionTitle!=null){if(typeof $scope.form.pollOptions==="undefined"||$scope.form.pollOptions==""){$scope.form.pollOptions=[];}
var newOption={'title':optionTitle};$scope.form.pollOptions.push(newOption);}}
$scope.removePollOption=function(item,index){$scope.form.pollOptions.splice(index,1);}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/polls/'+id).then(function(data){$scope.changeView('edit');$scope.form=data;showHideLoad(true);});}
$scope.saveEdit=function(){showHideLoad();dataFactory.httpRequest('index.php/admin/polls/'+$scope.form.id,'POST',{},$scope.form).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.polls=apiModifyTable($scope.polls,response.id,response);$scope.changeView('list');}
showHideLoad(true);});}
$scope.saveAdd=function(){showHideLoad();dataFactory.httpRequest('index.php/admin/polls','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.polls.push(response);$scope.changeView('list');}
showHideLoad(true);});}
$scope.makeActive=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/polls/active/'+id,'POST',{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){angular.forEach($scope.polls,function(item){item.pollStatus=0;if(item.id==response.id){item.pollStatus=1;}});}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.controller('feeGroupController',function(dataFactory,$rootScope,$scope){$scope.feeGroups={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.listAll=function(){dataFactory.httpRequest('index.php/admin/feeGroups/listAll').then(function(data){$scope.feeGroups=data;showHideLoad(true);});}
$scope.listAll();$scope.activeKey=function(item){var confirmRemove=confirm('الموافقة');if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admin/schoolActive/'+item.user+'/'+item.id,'POST').then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.listAll();}
showHideLoad(true);});}}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.controller('dbexportsController',function(dataFactory,$rootScope,$scope){$scope.classes={};$scope.views={};$scope.messages={};$scope.views.list=true;$scope.form={};$scope.form.selectedUsers=[];$scope.formS={};$scope.sendNewScope="form";showHideLoad(true);$scope.loadNotifications=function(page){dataFactory.httpRequest('index.php/admin/mobileNotif/listAll/'+page).then(function(data){$scope.subject_list=data.subject_list;$scope.messages=data.items;$scope.totalItems=data.totalItems;showHideLoad(true);});}
$scope.changeView=function(view){if(view=="send"){$scope.form={};}
$scope.views.send=false;$scope.views.list=false;$scope.views.settings=false;$scope.views[view]=true;}});OraSchool.controller('rolesController',function(dataFactory,$sce,$rootScope,$scope){$scope.roles={};$scope.roles_perms={};$scope.views={};$scope.views.list=true;$scope.pageNumber=1;$scope.form={};$scope.load_data=function(){dataFactory.httpRequest('index.php/admin/roles/listAll').then(function(data){$scope.roles=data.roles;$scope.districtZone=data.districtZone;$scope.cities=data.cities;$scope.perms_types=data.perms_types;$scope.roles_perms=data.roles_perms;showHideLoad(true);});}
$scope.load_data();$scope.saveAdd=function(data){showHideLoad();dataFactory.httpRequest('index.php/admin/roles','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.load_data();$scope.changeView('list');}
showHideLoad(true);});}
$scope.remove=function(item,index){var confirmRemove=confirm('سيتم الحذف هل توافق ؟');if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admin/roles/delete/'+item.id,'POST').then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.roles.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/admin/roles/'+id).then(function(data){$scope.changeView('edit');$scope.form=data;showHideLoad(true);});}
$scope.saveEdit=function(data){dataFactory.httpRequest('index.php/admin/roles/'+$scope.form.id,'POST',{},$scope.form).then(function(data){showHideLoad();response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_data();$scope.changeView('list');}
showHideLoad(true);});}
$scope.status=function(id,$index){showHideLoad();dataFactory.httpRequest('index.php/admin/roles/active/'+id,'POST').then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_data();}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});