if(jQuery){var originalFn=$.fn.data;$.fn.data=function(){if(arguments[0]!=='$binding')
return originalFn.apply(this,arguments);}}
var showHideLoad=function(hideIndicator){if(typeof hideIndicator==="undefined"||hideIndicator===null){$('#overlay').show();}else{$('#overlay').hide();}}
function goTop(){$("html,body").animate({scrollTop:0},500);}
var OraSchool=angular.module('OraSchool',['ngRoute','ngCookies','ui.autocomplete','angularUtils.directives.dirPagination','timer']).run(function($http,dataFactory,$rootScope,$q,$timeout,$location){$rootScope.title=" |  الإدارة العامة للاختبارات ";$rootScope.defaultAcademicYear=function(){angular.forEach($rootScope.dashboardData.academicYear,function(item){if(item.isDefault=="1"){return item.id;}});}
console.log($location.$$absUrl);$rootScope.gotoAnchor=function(x){var newHash='anchor'+x;if($location.hash()!==newHash){$location.hash('anchor'+x);}else{$anchorScroll();}};$rootScope.mm_select_upload=function(files,errFiles){if(files==null||files.length==0){$rootScope.media_manager=!$rootScope.media_manager;$rootScope.gallery_return_scope();}else{$rootScope.files=files;$rootScope.errFiles=errFiles;$rootScope.mm_files_count=0;if($rootScope.allow_multiple==false){files_tmp=files;files=[];files.push(files_tmp);}
angular.forEach(files,function(file){if(typeof file.uploaded=="undefined"){showHideLoad();}});}}
$rootScope.mm_cancel=function(){$rootScope.selected_images=[];$rootScope.media_manager=!$rootScope.media_manager;$rootScope.modalClass="";}
$rootScope.mm_upload_selected=function(){if(!$rootScope.allow_multiple){$('.mm_gallery_image_selected').removeClass('mm_gallery_image_selected');$rootScope.selected_images=[];}}
$rootScope.rat_cancel=function(){$rootScope.rate_model=!$rootScope.rate_model;}
$rootScope.view_rate=function(){$rootScope.modalClass="modal-lg";$rootScope.modalTitle="تقييم الموقع";$rootScope.rate_model=!$rootScope.rate_model;}
$rootScope.mm_open=function(){$rootScope.selected_images=[];$rootScope.gallery_images=[];$rootScope.media_manager=!$rootScope.media_manager;if($rootScope.show_gallery==true&&$rootScope.gallery_images.length==0){dataFactory.httpRequest('index.php/ml_upload/load').then(function(data){angular.forEach(data,function(file){$rootScope.gallery_images.push(file);$rootScope.mm_last_id=file.id;});});}}
$rootScope.mm_load_more=function(){$('.mm_load_more_loading').show();dataFactory.httpRequest('index.php/ml_upload/load/'+$rootScope.mm_last_id).then(function(data){if(data.length<25){$('.mm_load_more').hide();}
angular.forEach(data,function(file){$rootScope.gallery_images.push(file);$rootScope.mm_last_id=file.id;});$('.mm_load_more_loading').hide();});}
$rootScope.mm_select_image=function(file,$event){var element=angular.element($event.target);if($(element).hasClass('mm_gallery_image_selected')){$(element).removeClass('mm_gallery_image_selected');angular.forEach($rootScope.selected_images,function(image,key){if(image.id==file.id){delete $rootScope.selected_images.splice(key,1);}});}else{if($rootScope.allow_multiple){$rootScope.selected_images.push(file);}else{$rootScope.mm_files=null;$('.mm_gallery_image_selected').removeClass('mm_gallery_image_selected');$rootScope.selected_images=[];$rootScope.selected_images.push(file);}
$(element).addClass('mm_gallery_image_selected');}}
$rootScope.can=function(perm){if($rootScope.dashboardData.perms.indexOf(perm)!==-1){return true}
return false;}});OraSchool.controller('reqController',function(dataFactory,$routeParams,$scope,$sce,$rootScope,$route,$location){goTop();$scope.invoices={};$scope.students={};$scope.classes={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.invoice={};$scope.payDetails={};$scope.rowCities=[];$scope.resultDataErr=1;$scope.selectedTap=1;$scope.cgType=0;$scope.form.paymentRows=[];$scope.resultData={};$scope.typeData={"8":{"title":"تنسيق طلاب الثانوية العامة المتفوقين","desc":"المتفوقين : صورة  استمارة الثانوية العامة","id":"8",},"6":{"title":"تنسيق فئة الفقراء","desc":"فئة الفقراء : كرت ضمان اجتماعي او حكم او وثيقة تؤيد حالتة","id":"6",},"9":{"title":"تنسيق ابناء المحافظات المحرومة","desc":"المحافظات المحرومة : صورة الشهادة","id":"9",},};$scope.searchInput={};$scope.folderId='';$scope.userRole=$rootScope.dashboardData.role;$scope.cur_page=1;var methodName=$route.current.methodName;$scope.addPaymentRow=function(){if(typeof($scope.form.paymentRows)=="undefined"){$scope.form.paymentRows=[];}
if($scope.form.paymentRows.length<3){$scope.paymentRowsCount+=1;$scope.form.paymentRows.push({'ins_type':-1,'ins_city':-1,'ins_id':-1,'sec_id':-1,'err':""});}}
$scope.listInvoices=function(){showHideLoad();dataFactory.httpRequest('index.php/inv/data').then(function(data){$scope.cities=data.cities;$scope.citiesByType=data.citiesByType;$scope.citiesInst=data.citiesInst;$scope.citiesInstByType=data.citiesInstByType;$scope.citiesAvr=data.citiesAvr;$scope.instTypes=data.instTypes;$scope.instSecs={};$scope.instSecs2={};$scope.classes=data.classes;showHideLoad(true);});dataFactory.httpRequest('index.php/inv/overviews').then(function(data){if(!typeof(data.cities)=="undefined"){$scope.cities=data.cities;}
if(!typeof(data.typesInst)=="undefined"){$scope.citiesInstByType=data.typesInst;}
if(!typeof(data.citiesInst)=="undefined"){$scope.citiesInst=data.citiesInst;$scope.citiesByType=data.citiesInst;}});}
$scope.startAdd=function(id){$scope.form={};$scope.resultDataErr=1;$scope.selectedTap=1;$scope.changeView('add');}
$scope.viewTap=function(index){$scope.selectedTap=index;}
$scope.printCertificate2=function(){showHideLoad();setTimeout(function(){var mywindow=window.open('','new div','height=800,width=1200');mywindow.document.write('<html dir="rtl"><head><title>Print Certificates</title>');mywindow.document.write(' <link rel="stylesheet" href="css/bootstrap.min.css">  <link rel="stylesheet" href="css/shortcode/shortcodes.css">  <link rel="stylesheet" href="style.css"> <link rel="stylesheet" href="css/responsive.css"> <link rel="stylesheet" href="css/custom.css"> <link href="http://localhost/o/tanseek/assets/css/custom.css" id="theme" rel="stylesheet"><link href="http://localhost/o/tanseek/assets/css/style-rtl1.css" rel="stylesheet"><link href="http://localhost/o/tanseek/assets/css/main.css" rel="stylesheet"> <link href="http://localhost/o/tanseek/assets/css/intlTelInput.css" rel="stylesheet">  <script src="js/vendor/modernizr-2.8.3.min.js"></script><style> @media print { .no-print, .no-print * { display: none !important; } }</style>');mywindow.document.write('</head><body ><center><div class="no-print" style="padding:10px"><button type="button" onClick="window.print();">Print Certificates</button></style></center>');mywindow.document.write($('#printableArea2').html());mywindow.document.write('</body></html>');return true;},500);showHideLoad(true);}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.paymentRowsCount=0;$scope.folderId='';$scope.resultData=[];$scope.form={};$scope.resultDataErr=1;$scope.selectedTap=1;}
if(view=="add"){$scope.listInvoices();$scope.paymentRowsCount=0;$scope.resultData=[];$scope.form={};$scope.resultDataErr=1;$scope.selectedTap=1;$scope.addPaymentRow();$scope.addPaymentRow();$scope.addPaymentRow();$scope.addPaymentRow();}
if(view=="list"){$location.path("/req");}
$scope.views.list=false;$scope.views.details=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}
if($routeParams.reqId){$scope.instSecs={};$scope.instSecs2={};$scope.form={};$scope.resultDataErr=1;$scope.selectedTap=1;if($routeParams.reqId!='9'&&$routeParams.reqId!='8'&&$routeParams.reqId!='6'){$scope.selectedType={};$scope.changeView('list');}else{$scope.selectedType=$scope.typeData[$routeParams.reqId];$scope.changeView('add');}}else{$scope.selectedType={};$scope.form={};$scope.resultDataErr=1;$scope.selectedTap=1;$scope.changeView('list');}
$scope.getCitesByType=function(cgType){$scope.def.ins_type=cgType.ins_type;$scope.cgType=cgType.ins_type;}
$scope.getCertTypes=function(){$scope.classes={};$scope.rowCitiesInst=[];$scope.instSecs={};$scope.instSecs2={};$scope.form.classId=null;showHideLoad();dataFactory.httpRequest('index.php/certTypes','POST',{},{"ins_type":$scope.form.ins_type}).then(function(data){$scope.classes=data;showHideLoad(true);});}
$scope.getCertTypes2=function(){showHideLoad();dataFactory.httpRequest('index.php/certTypes','POST',{},{}).then(function(data){$scope.classes=data;showHideLoad(true);});}
$scope.getRowCertTypes=function(index,gkey){$scope.def.ins_city=gkey.ins_city;$scope.form.paymentRows[index].ins_id=null;$scope.form.paymentRows[index].sec_id=null;}
$scope.getRowMajors2=function(index,item){$scope.form.paymentRows[index].sec_id=null;if(typeof $scope.instSecs[item.ins_id]=="undefined"){$scope.instSecs[item.ins_id]=[];}
showHideLoad();dataFactory.httpRequest('index.php/getSections/'+item.ins_id).then(function(data){$scope.instSecs[item.ins_id]=data[item.ins_id];showHideLoad(true);});}
$scope.getRowMajors=function(index,item){$scope.form.paymentRows[index].sec_id=null;if(typeof $scope.instSecs2[item.ins_id]=="undefined"){$scope.instSecs2[item.ins_id]=[];}
showHideLoad();dataFactory.httpRequest('index.php/getSections2/'+item.ins_id,'POST',{},$scope.resultData).then(function(data){$scope.instSecs2[item.ins_id]=data[item.ins_id];showHideLoad(true);});}
if(methodName=="dueinvoices"){$scope.searchInput.dueInv=true;}
$scope.showModal=false;$scope.totalItems=0;$scope.saveAdd=function(data)
{if($routeParams.reqId){$scope.form.resultData=$scope.resultData;dataFactory.httpRequest('index.php/savReq/'+$routeParams.reqId,'POST',{},$scope.form,"fileDoc,").then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.resultData=[];$scope.form={};$scope.folderId=data.folderId;$scope.changeView('details');goTop();$scope.resultDataErr=1;$scope.selectedTap=1;}
if(data.status=="failed"){if(typeof(data.data)!="undefined"){if(typeof(data.data.tab)!="undefined"){$scope.viewTap(data.data.tab);}
if(typeof(data.data.err)!="undefined"&&data.data.err=="sec"){$scope.form.paymentRows[data.data.key].err=data.message;}}}
showHideLoad(true);});}}
$scope.searchSet=function(){if($routeParams.reqId){showHideLoad();dataFactory.httpRequest('index.php/resultSearch/'+$routeParams.reqId,'POST',{},$scope.form).then(function(data){response=apiResponse(data);if(data.err==0){$scope.resultData=data;$scope.form.resultData=$scope.resultData;$scope.resultDataErr=0;$scope.form.resSum=data.Total;$scope.viewTap(2);}
showHideLoad(true);});}}
$scope.classYears=function(){showHideLoad();dataFactory.httpRequest('index.php/resultsYears','POST',{},{"class":9}).then(function(data){data=apiResponse(data);$scope.years=data.years;$scope.classes=data.classes;showHideLoad(true);});}
$scope.classYears();$scope.TeachTestInArray=function(Object,val)
{return TestInArray(Object,val);}
$scope.save_publish=function(){if($scope.views.add){$scope.saveAdd();}else{$scope.saveEdit();}}
$scope.isItemSelected=function(arrayData,valueData){return arrayData.indexOf(valueData)>-1;}
$scope.paymentRowsCount=0;$scope.def={};$scope.def.ins_type=-1;$scope.def.classId=-1;$scope.def.ins_city=-1;$scope.removeRow=function(row,index){$scope.paymentRowsCount-=1;$scope.form.paymentRows.splice(index,1);}});OraSchool.controller('newsController',function(dataFactory,$routeParams,$sce,$rootScope,$scope){document.title="الاخبار"+$rootScope.title;$scope.newsboard={};$scope.newsboardTemp={};$scope.totalItemsTemp={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.userRole;if($routeParams.newsId){showHideLoad();dataFactory.httpRequest('index.php/news/'+$routeParams.newsId).then(function(data){$scope.form=data;$scope.newsTitle=data.newsTitle;$scope.newsImage=data.newsImage;$scope.newsText=$sce.trustAsHtml(data.newsText);$scope.changeView('read');showHideLoad(true);});}else{$scope.totalItems=0;$scope.pageChanged=function(newPage){getResultsPage(newPage);};getResultsPage(1);}
function getResultsPage(pageNumber){showHideLoad();if(!$.isEmptyObject($scope.newsboardTemp)){dataFactory.httpRequest('index.php/news/search/'+$scope.searchText+'/'+pageNumber).then(function(data){angular.forEach(data.newsboard,function(item){item.newsText=$sce.trustAsHtml(item.newsText);});$scope.newsboard=data.newsboard;$scope.totalItems=data.totalItems;showHideLoad(true);});}else{dataFactory.httpRequest('index.php/news/listAll/'+pageNumber).then(function(data){angular.forEach(data.newsboard,function(item){item.newsText=$sce.trustAsHtml(item.newsText);});$scope.newsboard=data.newsboard;$scope.userRole=data.userRole;$scope.totalItems=data.totalItems;showHideLoad(true);});}}
$scope.searchDB=function(){if($scope.searchText.length>=3){if($.isEmptyObject($scope.newsboardTemp)){$scope.newsboardTemp=$scope.newsboard;$scope.totalItemsTemp=$scope.totalItems;$scope.newsboard={};}
getResultsPage(1);}else{if(!$.isEmptyObject($scope.newsboardTemp)){$scope.newsboard=$scope.newsboardTemp;$scope.totalItems=$scope.totalItemsTemp;$scope.newsboardTemp={};}}}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.form.newsText="";}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.controller('enquiries',function(dataFactory,$sce,$rootScope,$scope,$routeParams){$scope.enquiries={};$scope.enq_type={};$scope.enq_source={};$scope.views={};$scope.views.list=true;$scope.pageNumber=1;$scope.form={};$scope.load_data=function(pageNumber){if(typeof pageNumber=="undefined"){pageNumber=$scope.pageNumber;}
$scope.pageNumber=pageNumber;if(!$.isEmptyObject($scope.enquiriesTemp)){showHideLoad();dataFactory.httpRequest('index.php/enquiries/search/'+$scope.searchText+'/'+pageNumber).then(function(data){$scope.enquiries=data.enquiries;$scope.totalItems=data.totalItems;showHideLoad(true);});}else{showHideLoad();dataFactory.httpRequest('index.php/enquiries/listAll/'+pageNumber).then(function(data){$scope.enquiries=data.enquiries;if(pageNumber==1){$scope.enq_type=data.enq_type;$scope.enq_source=data.enq_source;}
$scope.totalItems=data.totalItems;showHideLoad(true);});}}
$scope.pageChanged=function(newPage){$scope.load_data(newPage);};$scope.listAnswers=function(id){showHideLoad();dataFactory.httpRequest('index.php/listAnswers/enquiries/'+id).then(function(data){$scope.answers=data;$scope.changeView('answers');showHideLoad(true);});}
$scope.searchDB=function(){if($scope.searchText.length>=3){if($.isEmptyObject($scope.enquiriesTemp)){$scope.enquiriesTemp=$scope.enquiries;$scope.totalItemsTemp=$scope.totalItems;$scope.enquiries={};}
$scope.load_data(1);}else{if(!$.isEmptyObject($scope.enquiriesTemp)){$scope.enquiries=$scope.enquiriesTemp;$scope.totalItems=$scope.totalItemsTemp;$scope.enquiriesTemp={};}}}
$scope.view_details=function(id){showHideLoad();dataFactory.httpRequest('index.php/enquiries/view/'+id).then(function(data){$scope.form=data;$scope.changeView('view');showHideLoad(true);});}
if($routeParams.viewId){$scope.view_details($routeParams.viewId);}else{$scope.load_data();}
$scope.saveAdd=function(data){showHideLoad();dataFactory.httpRequest('index.php/enquiries','POST',{},$scope.form,"enq_file,").then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.load_data();$scope.changeView('list');}
showHideLoad(true);});}
$scope.remove=function(item,index){var confirmRemove=confirm($rootScope.phrase.sureRemove);if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/enquiries/delete/'+item.id,'POST').then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.enquiries.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/enquiries/'+id).then(function(data){$scope.changeView('edit');$scope.form=data;showHideLoad(true);});}
$scope.saveEdit=function(data){dataFactory.httpRequest('index.php/enquiries/'+$scope.form.id,'POST',{},$scope.form,"enq_file,").then(function(data){showHideLoad();response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_data();$scope.changeView('list');}
showHideLoad(true);});}
$scope.status=function(id,$index){showHideLoad();dataFactory.httpRequest('index.php/enquiries/active/'+id,'POST').then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_data();}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.enq_desc="";}
$scope.views.list=false;$scope.views.add=false;$scope.views.answers=false;$scope.views.edit=false;$scope.views.view=false;$scope.views[view]=true;}});OraSchool.controller('complaints',function(dataFactory,$sce,$rootScope,$scope,$routeParams){$scope.complaints={};$scope.comp_type={};$scope.comp_source={};$scope.views={};$scope.views.list=true;$scope.pageNumber=1;$scope.form={};$scope.load_data=function(pageNumber){if(typeof pageNumber=="undefined"){pageNumber=$scope.pageNumber;}
$scope.pageNumber=pageNumber;if(!$.isEmptyObject($scope.complaintsTemp)){showHideLoad();dataFactory.httpRequest('index.php/complaints/search/'+$scope.searchText+'/'+pageNumber).then(function(data){$scope.complaints=data.complaints;$scope.totalItems=data.totalItems;showHideLoad(true);});}else{showHideLoad();dataFactory.httpRequest('index.php/complaints/listAll/'+pageNumber).then(function(data){$scope.complaints=data.complaints;if(pageNumber==1){$scope.comp_type=data.comp_type;$scope.comp_source=data.comp_source;}
$scope.totalItems=data.totalItems;showHideLoad(true);});}}
$scope.listAnswers=function(id){showHideLoad();dataFactory.httpRequest('index.php/listAnswers/complaints/'+id).then(function(data){$scope.answers=data;$scope.changeView('answers');showHideLoad(true);});}
$scope.pageChanged=function(newPage){$scope.load_data(newPage);};$scope.searchDB=function(){if($scope.searchText.length>=3){if($.isEmptyObject($scope.complaintsTemp)){$scope.complaintsTemp=$scope.complaints;$scope.totalItemsTemp=$scope.totalItems;$scope.complaints={};}
$scope.load_data(1);}else{if(!$.isEmptyObject($scope.complaintsTemp)){$scope.complaints=$scope.complaintsTemp;$scope.totalItems=$scope.totalItemsTemp;$scope.complaintsTemp={};}}}
$scope.view_details=function(id){showHideLoad();dataFactory.httpRequest('index.php/complaints/view/'+id).then(function(data){$scope.form=data;$scope.changeView('view');showHideLoad(true);});}
if($routeParams.viewId){$scope.view_details($routeParams.viewId);}else{$scope.load_data();}
$scope.saveAdd=function(data){showHideLoad();dataFactory.httpRequest('index.php/complaints','POST',{},$scope.form,"enq_file,").then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.load_data();$scope.changeView('list');}
showHideLoad(true);});}
$scope.remove=function(item,index){var confirmRemove=confirm($rootScope.phrase.sureRemove);if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/complaints/delete/'+item.id,'POST').then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.complaints.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/complaints/'+id).then(function(data){$scope.changeView('edit');$scope.form=data;showHideLoad(true);});}
$scope.saveEdit=function(data){dataFactory.httpRequest('index.php/complaints/'+$scope.form.id,'POST',{},$scope.form,"enq_file,").then(function(data){showHideLoad();response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_data();$scope.changeView('list');}
showHideLoad(true);});}
$scope.status=function(id,$index){showHideLoad();dataFactory.httpRequest('index.php/complaints/active/'+id,'POST').then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_data();}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.comp_desc="";}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views.answers=false;$scope.views.view=false;$scope.views[view]=true;}});OraSchool.config(function($logProvider){$logProvider.debugEnabled(false);});var appBaseUrl=$('base').attr('href');OraSchool.controller('mainController',function(dataFactory,$rootScope,$route,$scope){$scope.chgAcYearModal=function(){$scope.modalTitle=$scope.phrase.chgYear;$scope.chgAcYearModalShow=!$scope.chgAcYearModalShow;}
$scope.page_title="mainController";$scope.chgAcYear=function(){showHideLoad();dataFactory.httpRequest('index.php/dashboard/changeAcYear','POST',{},{year:$scope.dashboardData.selectedAcYear}).then(function(data){$scope.chgAcYearModalShow=!$scope.chgAcYearModalShow;showHideLoad(true);location.reload();});}
$scope.savePollVote=function(){showHideLoad();if($scope.dashboardData.polls.selected===undefined){alert($scope.phrase.voteMustSelect);showHideLoad(true);return;}
dataFactory.httpRequest('index.php/dashboard/polls','POST',{},$scope.dashboardData.polls).then(function(data){data=successOrError(data);if(data){$scope.dashboardData.polls=data;}
showHideLoad(true);});}
$scope.adminHasPerm=function(perm){return $rootScope.dashboardData.perms.some(function(s){return s.indexOf(perm)>-1;});}
$scope.changeTheme=function(theme){$('#theme').attr({href:'assets/css/colors/'+theme+'.css'})
$rootScope.dashboardData.baseUser.defTheme=theme;var updatePost={'spec':'defTheme','value':theme};dataFactory.httpRequest('index.php/accountSettings/profile','POST',{},updatePost).then(function(data){response=apiResponse(data,'edit');});$('#themecolors').on('click','a',function(){$('#themecolors li a').removeClass('working');$(this).addClass('working')});}
$scope.changeLang=function(theme){var updatePost={'spec':'defLang','value':theme};dataFactory.httpRequest('index.php/accountSettings/profile','POST',{},updatePost).then(function(data){response=apiResponse(data,'edit');});setTimeout(function(){location.reload();},500);}
showHideLoad(true);});OraSchool.controller('dashboardController',function(dataFactory,$rootScope,$scope){goTop();dataFactory.httpRequest('index.php/overviews').then(function(data){$rootScope.dashboardData.overviews=data;showHideLoad(true);});});OraSchool.controller('payController',function(dataFactory,$rootScope,$scope){goTop();$scope.search=function(){showHideLoad();dataFactory.httpRequest('index.php/getFoldar/'+$scope.form.folderId,'POST',{},{}).then(function(data){$scope.form=data;data=apiResponse(data);showHideLoad(true);});}
$scope.saveAdd=function(){showHideLoad();dataFactory.httpRequest('index.php/startPay/'+$scope.form.folderId,'POST',{},$scope.form).then(function(data){$scope.form=data;data=apiResponse(data);showHideLoad(true);});}});