OraSchool.controller('tableController',function(dataFactory,$scope,$sce,$rootScope,$route){$scope.items={};$scope.filters={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.searchInput={};$scope.userRole=$rootScope.dashboardData.role;$scope.cur_page=1;var methodName=$route.current.methodName;$scope.totalItems=0;$scope.methodName=$route.current.methodName;$scope.listItems=function(pageNumber){showHideLoad();dataFactory.httpRequest('index.php/'+$scope.methodName+'List/listAll/'+pageNumber).then(function(data){$scope.items=data.items;$scope.filters=data.filters;$scope.totalItems=data.totalItems;showHideLoad(true);});}
$scope.searchDB=function(pageNumber){showHideLoad();dataFactory.httpRequest('index.php/'+$scope.methodName+'List/listAll/'+pageNumber,'POST',{},{'searchInput':$scope.searchInput}).then(function(data){$scope.items=data.items;$scope.totalItems=data.totalItems;showHideLoad(true);});}
$scope.getResultsPage=function(id){if(typeof id=="undefined"){id=$scope.cur_page;}
$scope.cur_page=id;if(!jQuery.isEmptyObject($scope.searchInput)){$scope.searchDB(id);}else{$scope.listItems(id);}}
$scope.getResultsPage(1);$scope.showModal=false;$scope.saveAdd=function(){showHideLoad();dataFactory.httpRequest('index.php/'+$scope.methodName+'','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}
$scope.saveEdit=function(){dataFactory.httpRequest('index.php/'+$scope.methodName+'/'+$scope.form.id,'POST',{},$scope.form).then(function(data){showHideLoad();response=apiResponse(data,'edit');if(data.status=="success"){$scope.getResultsPage();$scope.changeView('list');}
showHideLoad(true);});}
$scope.remove=function(item,index){var confirmRemove=confirm($rootScope.phrase.sureRemove);if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/'+$scope.methodName+'/delete/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.items.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/'+$scope.methodName+'/'+id).then(function(data){$scope.form=data;$scope.changeView('edit');showHideLoad(true);});}
$scope.userProfile=function(id){dataFactory.httpRequest('index.php/user/profile/'+id).then(function(data){$scope.modalTitle=data.title;$scope.modalContent=$sce.trustAsHtml(data.content);$scope.showModal=!$scope.showModal;});};$scope.resetSearch=function(){$scope.searchInput={};$scope.getResultsPage(1);}
$scope.pageChanged=function(newPage){$scope.getResultsPage(newPage);};$scope.import=function(){$scope.changeView('import');};$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views.import=false;$scope.views.details=false;$scope.views[view]=true;}});OraSchool.controller('studentsController',function(dataFactory,$scope,$sce,$rootScope,$route){$scope.students={};$scope.classes={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.invoice={};$scope.payDetails={};$scope.resultData={};$scope.searchInput={};$scope.userRole=$rootScope.dashboardData.role;$scope.cur_page=1;var methodName=$route.current.methodName;$scope.listInvoices=function(pageNumber){showHideLoad();dataFactory.httpRequest('index.php/studentsList/listAll/'+pageNumber).then(function(data){$scope.students=data.students;$scope.classes=data.classes;$scope.cities=data.cities;$scope.years=data.years;$scope.showUser=data.showUser;$scope.totalItems=data.totalItems;$scope.currency_symbol=data.currency_symbol;showHideLoad(true);});}
$scope.searchDB=function(pageNumber){showHideLoad();dataFactory.httpRequest('index.php/studentsList/listAll/'+pageNumber,'POST',{},{'searchInput':$scope.searchInput}).then(function(data){$scope.students=data.students;$scope.totalItems=data.totalItems;showHideLoad(true);});}
$scope.getResultsPage=function(id){if(typeof id=="undefined"){id=$scope.cur_page;}
$scope.cur_page=id;if(!jQuery.isEmptyObject($scope.searchInput)){$scope.searchDB(id);}else{$scope.listInvoices(id);}}
$scope.getResultsPage(1);$scope.showModal=false;$scope.userProfile=function(id){dataFactory.httpRequest('index.php/user/profile/'+id).then(function(data){$scope.modalTitle=data.title;$scope.modalContent=$sce.trustAsHtml(data.content);$scope.showModal=!$scope.showModal;});};$scope.toggleSearch=function(){$('.advSearch').toggleClass('col-0 col-3 hidden',1000);$('.listContent').toggleClass('col-12 col-9',1000);}
$scope.resetSearch=function(){$scope.searchInput={};$scope.getResultsPage(1);}
$scope.totalItems=0;$scope.pageChanged=function(newPage){$scope.getResultsPage(newPage);};$scope.import=function(){$scope.changeView('import');};$scope.saveImported=function(content){dataFactory.httpRequest('index.php/import/'+$scope.formx.impclass,'POST',{},$scope.formx,"import,").then(function(data){data=apiResponse(data);if(typeof data.status!="undefined"){if(data.status=="success"){$scope.changeView('list');}}});showHideLoad(true);}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views.invoice=false;$scope.views.import=false;$scope.views.details=false;$scope.views[view]=true;}});OraSchool.controller('adminsController',function(dataFactory,$rootScope,$scope){$scope.admins={};$scope.roles={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.form.comVia=["mail","sms","phone"];$scope.form.customPermissions=[];$scope.load_admins=function(){dataFactory.httpRequest('index.php/admins/listAll').then(function(data){$scope.admins=data.admins;$scope.roles=data.roles;$scope.changeView('list');showHideLoad(true);});}
$scope.load_admins();$scope.saveAdd=function(content){response=apiResponse(content,'add');if(content.status=="success"){showHideLoad();$scope.load_admins();}
showHideLoad(true);}
$scope.remove=function(item,index){var confirmRemove=confirm($rootScope.phrase.sureRemove);if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/admins/delete/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.admins.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/admins/'+id).then(function(data){$scope.form=data;$scope.changeView('edit');showHideLoad(true);});}
$scope.hasPermission=function(permission){var caseNow=$.inArray(permission,$scope.form.customPermissions)>-1;return caseNow;}
$scope.saveEdit=function(content){response=apiResponse(content,'edit');if(content.status=="success"){showHideLoad();$scope.load_admins();}
showHideLoad(true);}
$scope.account_status=function(user_id,$index){showHideLoad();dataFactory.httpRequest('index.php/admins/account_status/'+user_id,'POST',{},{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.admins[$index].account_active=response.account_active;}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.form.comVia=["mail","sms","phone"];}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.controller('employeesController',function(dataFactory,$rootScope,$scope){$scope.admins={};$scope.roles={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.form.comVia=["mail","sms","phone"];$scope.form.customPermissions=[];$scope.load_admins=function(){dataFactory.httpRequest('index.php/employees/listAll').then(function(data){$scope.admins=data.admins;$scope.roles=data.roles;$scope.districtZone=data.districtZone;$scope.feeGroups=data.feeGroups;$scope.changeView('list');showHideLoad(true);});}
$scope.load_admins();$scope.saveAdd=function(data){showHideLoad();dataFactory.httpRequest('index.php/employees','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.load_admins();$scope.changeView('list');}
showHideLoad(true);});}
$scope.saveEdit=function(data){dataFactory.httpRequest('index.php/employees/'+$scope.form.id,'POST',{},$scope.form).then(function(data){showHideLoad();response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_admins();$scope.changeView('list');}
showHideLoad(true);});}
$scope.remove=function(item,index){var confirmRemove=confirm($rootScope.phrase.sureRemove);if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/employees/delete/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.admins.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/employees/'+id).then(function(data){$scope.form=data;$scope.changeView('edit');showHideLoad(true);});}
$scope.hasPermission=function(permission){var caseNow=$.inArray(permission,$scope.form.customPermissions)>-1;return caseNow;}
$scope.account_status=function(user_id,$index){showHideLoad();dataFactory.httpRequest('index.php/employees/account_status/'+user_id,'POST',{},{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.admins[$index].account_active=response.account_active;}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.form.comVia=["mail","sms","phone"];}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.controller('usersController',function(dataFactory,$rootScope,$scope){$scope.admins={};$scope.roles={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.form.comVia=["mail","sms","phone"];$scope.form.customPermissions=[];$scope.load_admins=function(){dataFactory.httpRequest('index.php/users/listAll').then(function(data){$scope.admins=data.admins;$scope.roles=data.roles;$scope.changeView('list');showHideLoad(true);});}
$scope.load_admins();$scope.saveAdd=function(data){showHideLoad();dataFactory.httpRequest('index.php/users','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.load_admins();$scope.changeView('list');}
showHideLoad(true);});}
$scope.saveEdit=function(data){dataFactory.httpRequest('index.php/users/'+$scope.form.id,'POST',{},$scope.form).then(function(data){showHideLoad();response=apiResponse(data,'edit');if(data.status=="success"){$scope.load_admins();$scope.changeView('list');}
showHideLoad(true);});}
$scope.remove=function(item,index){var confirmRemove=confirm($rootScope.phrase.sureRemove);if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/users/delete/'+item.id,'POST',{},{}).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.admins.splice(index,1);}
showHideLoad(true);});}}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/users/'+id).then(function(data){$scope.form=data;$scope.changeView('edit');showHideLoad(true);});}
$scope.hasPermission=function(permission){var caseNow=$.inArray(permission,$scope.form.customPermissions)>-1;return caseNow;}
$scope.account_status=function(user_id,$index){showHideLoad();dataFactory.httpRequest('index.php/users/account_status/'+user_id,'POST',{},{}).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.admins[$index].account_active=response.account_active;}
showHideLoad(true);});}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};$scope.form.comVia=["mail","sms","phone"];}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});OraSchool.controller('reportsController',function(dataFactory,$rootScope,$scope,$http,$sce){$scope.views={};$scope.form={};$scope.views.list=true;$scope.stats={};showHideLoad();dataFactory.httpRequest('index.php/reportsAll','POST',{},{}).then(function(data){$scope.reports=data;showHideLoad(true);});$scope.changeView=function(view){$scope.views.list=false;$scope.views[view]=true;}});OraSchool.controller('langController',function(dataFactory,$rootScope,$scope){$scope.languages={};$scope.views={};$scope.views.list=true;$scope.form={};$scope.translate=function(){$(".phraseList label").each(function(i,current){var str=$(current).text();if($(current).children('input').val()==""){var str2=$(current).children('input').val(str);$(current).children('input').trigger('input');}});return;}
$scope.highlight=function(){$(".phraseList label").each(function(i,current){if($(current).children('input').val()==""){$(current).children('input').css('border','10px solid');}});return;}
$scope.addLangItemMulti=function(){var id=$scope.form.newMId;var newMulti=$scope.form.newMulti;var newOne=$scope.form.newOne;$scope.form.languagePhrases[id+'s']=newMulti;$scope.form.languagePhrases[id+'Title']='عنوان'+' '+'ال'+newOne;$scope.form.languagePhrases[id+'Content']='تفاصيل'+' '+'ال'+newOne;$scope.form.languagePhrases['add'+id]='اضافة'+' '+newOne;$scope.form.languagePhrases['edit'+id]='تعديل'+' '+newOne;$scope.form.languagePhrases['list'+id]='قائمة'+' '+listproduct;}
$scope.addLangItem=function(){$scope.form.languagePhrases[$scope.form.newId]=$scope.form.newName;}
dataFactory.httpRequest('index.php/languages/listAll').then(function(data){$scope.languages=data;showHideLoad(true);});$scope.addLang=function(){$scope.form={};$scope.form.languagePhrases={};$scope.changeView('edit');}
$scope.edit=function(id){showHideLoad();dataFactory.httpRequest('index.php/languages/'+id).then(function(data){$scope.changeView('edit');$scope.form=data;showHideLoad(true);});}
$scope.saveEdit=function(){if(typeof $scope.form.id=="undefined"){showHideLoad();dataFactory.httpRequest('index.php/languages','POST',{},$scope.form).then(function(data){response=apiResponse(data,'add');if(data.status=="success"){$scope.languages.push(response);$scope.changeView('list');}
showHideLoad(true);});}else{showHideLoad();dataFactory.httpRequest('index.php/languages/'+$scope.form.id,'POST',{},$scope.form).then(function(data){response=apiResponse(data,'edit');if(data.status=="success"){$scope.languages=apiModifyTable($scope.languages,response.id,response);$scope.changeView('list');}
showHideLoad(true);});}}
$scope.remove=function(item,index){var confirmRemove=confirm($rootScope.phrase.sureRemove);if(confirmRemove==true){showHideLoad();dataFactory.httpRequest('index.php/languages/delete/'+item.id,'POST',{},$scope.form).then(function(data){response=apiResponse(data,'remove');if(data.status=="success"){$scope.languages.splice(index,1);}
showHideLoad(true);});}}
$scope.saveAdd=function(){}
$scope.changeView=function(view){if(view=="add"||view=="list"||view=="show"){$scope.form={};}
$scope.views.list=false;$scope.views.add=false;$scope.views.edit=false;$scope.views[view]=true;}});